### ISSUE TITLE
Now I test ban hwid

### ISSUE THREAD

**Issue by cold-hr** [AsiaGenius/ring-0#2]
Now I test ban hwid
Players can also get into the game.

**Comment by cold-hr** [comment]
compile warning  gcc
![image](https://cloud.githubusercontent.com/assets/13975637/20674530/ef13c3bc-b5bb-11e6-9bf5-9a5496edc9f0.png)

**Comment by AsiaGenius** [comment]
Hey, wait last new release 2.13 please.

Ban HWID need > 24 hours delay.
