### ISSUE TITLE
Some warnings and client shutdown upon login

### ISSUE THREAD

**Issue by lelouch22** [AsiaGenius/ring-0#3]
Here are some warnings that i encountered...

```
loginclif.c: In function 'ring_reqauth_mac':
loginclif.c:283: warning: unused variable 'packet_len'
loginclif.c: At top level:
loginclif.c:240: warning: 'ring_check' defined but not used
```

```
1>c:\ring-0\info\infos\dllmain.cpp(103): warning C4715: 'CRCGRF' : not all control paths return a value
1>dllmain.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/INCREMENTAL:NO' specification
```

Also when i logged in my client suddenly shutdown
Client: 2013-12-23
![wew](https://cloud.githubusercontent.com/assets/4976551/20723920/5ccfa5ce-b6a7-11e6-84ed-ae53b0ba10f7.jpg)

**Comment by AsiaGenius** [comment]
This error was caused due to a packet copy failure. Wait for stable version 2.13 that will be released today.
