### ISSUE TITLE
--- Error 2544 - corrupted file detected (ring.dll or infos.dll)

### ISSUE THREAD

**Issue by hnomkeng** [AsiaGenius/ring-0#5]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Hnomkeng PC>cd c:\ring

c:\ring>ring_tools.exe

##########################
#       RING-0
##########################
#  1 = CRIPT GENERATOR
#  2 = KEY GENERATOR
#  3 = PCK SCANNER
#  4 = GET CLS
#  5 = DMP GENERATOR
#  6 = ววว TOOLS
##########################

Please enter tool option: 1

=== CRIPT GENERATOR ===

Please enter File Name: ring.dll
Your CRIPTO is: a973a0c09974ac1b7c19e1f1afe42bba
c:\ring>ring_tools.exe

##########################
#       RING-0
##########################
#  1 = CRIPT GENERATOR
#  2 = KEY GENERATOR
#  3 = PCK SCANNER
#  4 = GET CLS
#  5 = DMP GENERATOR
#  6 = ววว TOOLS
##########################

Please enter tool option: 1

=== CRIPT GENERATOR ===

Please enter File Name: infos.dll
Your CRIPTO is: d8bd46288be2b02c29bd3388bb46c8a4
c:\ring>ring_tools.exe

##########################
#       RING-0
##########################
#  1 = CRIPT GENERATOR
#  2 = KEY GENERATOR
#  3 = PCK SCANNER
#  4 = GET CLS
#  5 = DMP GENERATOR
#  6 = ววว TOOLS
##########################

Please enter tool option: 3

=== PCK SCANNER ===

Please enter your HEXED NAME: poringro.exe

wait...

Your PCK KEY: 419c144cf6f3392605aa31fd4b8c2d43

c:\ring>
rAthena
------------------------------------------------------- 
Active: 
 IP: 139.59.248.xxx
 Emulator: rAthena
 Expire: 
 Ring CRYPT: a973a0c09974ac1b7c19e1f1afe42bba
 Info CRYPT: d8bd46288be2b02c29bd3388bb46c8a4
 PCK CRYPT: 419c144cf6f3392605aa31fd4b8c2d43
 Hack Log: 0

**Comment by AsiaGenius** [comment]
https://github.com/AsiaGenius/ring-0/tree/master/Shield/GameGuard/SELECT%20YOUR%20MODE/PASSIVE%20MOD

Check

**Comment by hnomkeng** [comment]
passive mode is pass, i don't get hard mode.

how to setup hard mod ?

**Comment by AsiaGenius** [comment]
Fixed in last release
