### ISSUE TITLE
No Error log detected in GG Folder

### ISSUE THREAD

**Issue by Vexillio** [AsiaGenius/ring-0#6]
Client crashing after opening.

**Comment by AsiaGenius** [comment]
https://github.com/AsiaGenius/ring-0/tree/master/Shield/GameGuard/SELECT%20YOUR%20MODE/PASSIVE%20MOD

Check

**Comment by Vexillio** [comment]
Tried all already , but will try to rebuild infos again

**Comment by AsiaGenius** [comment]
nice, go to discord for more questions
