### ISSUE TITLE
have issue login for rathena.

### ISSUE THREAD

**Issue by hnomkeng** [AsiaGenius/ring-0#7]
[Status]: Request for connection of hnomkeng9 (ip: 180.180.34.xx) version=53
[Notice]: Authentication accepted (account: hnomkeng9, id: 2000006, ip: 180.180.34.xx)
[Status]: Connection of the account 'hnomkeng9' accepted.
[Status]: Ring-0: Connection refused invalid key 952f03f16a3393687d2fa628e37xxx
[Info]: Closed connection from '180.180.34.xx'.
[Info]: request connect - account_id:2000006/login_id1:1126290305/login_id2:322011243
[Status]: Ring0 - User Invalid
[Warning]: aid=2000006 has an incorect version=0 in clientinfo. Server compiled for 53

=== KEY GENERATOR ===
Please enter server IP: 103.58.149.xxx
Your server key is: f0431bbf14d7f462ab586aafeb4xxx

githhash : 98574189093dcabb772d0ffeb6542cbc88ce60a7
githash rathena : https://github.com/rathena/rathena/commit/2bb92a114bc21ab0128cf18eb70e5defae788daf
Client date : 2015-09-16

**Comment by AsiaGenius** [comment]
Send PM for Gary in Discord App chat.

**Comment by AsiaGenius** [comment]
disable packet obfuscation in hexed and emulator xD
